# site settings
title: RGCL
subtitle: University of Wolverhampton 
email: riilp@wlv.ac.uk
description: Website of the Research Group in Computational Linguistics<br />at the University of Wolverhampton
baseurl: "" # the subpath of your site, e.g. /blog
url: https://rgcl.wlv.ac.uk # the base hostname & protocol for your site
author: RGCL
university: University of Wolverhampton 
room_address: MC135 
building_address: Millenium City Building
street_address: Wulfruna Street
city: Wolverhampton 
state: 
zip_code: WV1 1LY
country: United Kingdom 
phone: +44 1902 321630 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Limit to latest news (e.g. 5 = only 5 latest ones)
news-count: 5

defaults:
  - scope:
      path: "medias"
    values:
      image: true
  - scope:
      path: ""
    values:
      author: "RGCL"

future: true

collections_dir: posts 
collections:
  news:
    output: true
  seminars:
    output: true

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
twitter_username: RGCL_WLV  # Twitter card in head.html
socials:
  Twitter: https://twitter.com/RGCL_WLV
  GitHub: https://github.com/wlv-rgcl
  Facebook: https://www.facebook.com/riilp.Wolverhampton
  Instagram: https://www.instagram.com/wlvuni
  rss: /feeds/news.atom
  GitLab:
  Google-Plus: 
  LinkedIn: 
  Slack:

# build settings
markdown: kramdown

permalink: pretty

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

plugins:
  - jekyll-feed

feed:
  collections:
    news:
      path: "/feeds/news.atom"
    seminars:
      path: "/feeds/seminars.atom"
